# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HLa+fxAZIAOu1gLL1StsneYWwxaQ/ceiExLmHEfWaj/yQ7fj9RrryO/GcB1mIseaZT51ipGae88CYlm5hALGlhCIQd8TnMXNc5vdvEuMTbMXdd4BG4fLfv/q/NEHZ6hSJ08SgqAYmG5PTQ/Aoxi6kTnCwznJKKFYrpQF/rZnXZ5TfWqK57gR7OtzBuw9daWi//grP63aTP66jcmXwRYg97FmTSYgQ/9ZIx8MOwajgRCGU7u2HeYoR0Z4K21DcvJf+bOw2lhj3nmriyD7scYOY0zT1Qb/ZSQdSz+C3byzNm5PhSTaSJFfHPHV9PC41qeZc6m3cXqyGZwTvjby3OPFdfD/radpBuHJqwUVApYUdZCLsYbq3Vf83Hln0jA+QfKUiOqWd4CRg9HXu1iFA+mqKapGSkSgIWruEb7mdIt5DWYP1LEo1yvi2+o/PV7CvH4sMNnCt1F+CecDYou4JDoJzx7OmhgoAd+8Ez/n8mcIlv0M/DYUO059ZPTCHyX2g7LAAPOm6s4jYz1X0WJX216GkSlR2jqtCS+vRLNbWqR/DBwkXke33xsqs19ZkM4RYE5SwwuleUcpHM864WojP2BOZJr7BWJ7aaIX4u5dFuWovI6DZ8t7S9u46zZc6qGvVZpCiSIsAbn3Dmqvw0WLkP1Ikvpt6FfmZkofxwaM6hHUMJk="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_numpy1.16python3.6.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_numpy1.16python3.7.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_numpy1.16python3.8.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_numpy1.18python3.6.____73_pypy UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"
  - export FEEDSTOCK_NAME=$(basename ${TRAVIS_REPO_SLUG})


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi